### PR TITLE
feat:  use slog handler

### LINKED ISSUE #15: Incompatible with expected Writer interface
The naming of the expected logger [interface for gorm](https://pkg.go.dev/gorm.io/gorm/logger#Interface) infers that the parameters are to be given to a `Print` like method however the [New method](https://pkg.go.dev/gorm.io/gorm/logger#New) which is the standard way to create a `Logger` takes a [Writer ](https://pkg.go.dev/gorm.io/gorm/logger#Writer) which defines `Printf` not `Print` so the expectation is `Printf(format string), a ...any)` not `Print(a ...any)`

The impact of that is errors thrown from gorm cause corrupt output:
```
msg="failed to initialize database, got error %v" !BADKEY="failed to connect to `host=localhost user=test_user database=test_database`: failed SASL auth (FATAL: password authentication failed for user \"test_user\" (SQLSTATE 28P01))"`
```

### PR DESCRIPTION
**Pull request by injeniero**
Using the handler directly allows to correctly set the Record.PC

This PR also fixes #15

### CODE REVIEW

**Review by stevenh — COMMENTED** [review]
This fixes the issue raised but also eliminates the benefit of a structure logger as everything is now just a `Sprintf`.

Is there a way where we can have `Info` and `Infof` etc?

**Comment by injeniero** [comment]
We can do that, but this is targeting GORM lib, and they use their interface as if it was a Sprintf call. It would be on them to extend their Interface and add new methods.

Why would you like to add methods that are not part of the interface?

**Comment by stevenh** [comment]
> We can do that, but this is targeting GORM lib, and they use their interface as if it was a Sprintf call. It would be on them to extend their Interface and add new methods.
> 
> Why would you like to add methods that are not part of the interface?

Would be nice to support a more structured approach, but that would require internal changes to gorm, so I think this is the best that can be done without a breaking change there.

**Comment by injeniero** [comment]
@stevenh coverage improved :-)

**Review by stevenh — APPROVED** [review]

**Comment by injeniero** [comment]
@orandin tagging you to get this rolling. Please let me know if you want something else changed. Thanks!!

**Comment by orandin** [comment]
@injeniero thank you for your great contribution and @stevenh for your review 🥳

**Pull request merged**
